### ISSUE TITLE
Import error with reader.PdbxReader

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/mmcif_pdbx#41]
As described in https://github.com/Electrostatics/pdb2pqr/issues/146 there is a problem with the import commands in mmcif_pdbx:

```
Traceback (most recent call last):
  File "/Users/bake113/opt/anaconda3/envs/pdb2pqr/bin/pdb2pqr30", line 33, in <module>
    sys.exit(load_entry_point('pdb2pqr', 'console_scripts', 'pdb2pqr30')())
  File "/Users/bake113/OneDrive - PNNL/Documents/Git/pdb2pqr/pdb2pqr/main.py", line 796, in main
    main_driver(args)
  File "/Users/bake113/OneDrive - PNNL/Documents/Git/pdb2pqr/pdb2pqr/main.py", line 735, in main_driver
    pdblist, is_cif = io.get_molecule(args.input_path)
  File "/Users/bake113/OneDrive - PNNL/Documents/Git/pdb2pqr/pdb2pqr/io.py", line 457, in get_molecule
    pdblist, errlist = cif.read_cif(input_file)
  File "/Users/bake113/OneDrive - PNNL/Documents/Git/pdb2pqr/pdb2pqr/cif.py", line 1037, in read_cif
    pdbdata = pdbx.load(cif_file)
  File "/Users/bake113/opt/anaconda3/envs/pdb2pqr/lib/python3.8/site-packages/pdbx/__init__.py", line 23, in load
    from .reader import PdbxReader
```

**Comment by sobolevnrm** [comment]
D'oh.  This is because I haven't released a new version to PyPI...

**Comment by sobolevnrm** [comment]
Actually, something is wrong with the PyPI version.  I think we just need to release a new, clean version.
