### ISSUE TITLE
pdb2pqr can't find mmcif_pdbx module although the latter is installed

### ISSUE THREAD

**Issue by dvdesolve** [Electrostatics/mmcif_pdbx#50]
**Describe the bug**
Probably it should be related to the pdb2pqr, but anyway, upon running pdb2pqr I get the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (mmcif-pdbx 0+unknown (/usr/lib/python3.9/site-packages), Requirement.parse('mmcif_pdbx>=1.1.2'), {'pdb2pqr'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pdb2pqr30", line 33, in <module>
    sys.exit(load_entry_point('pdb2pqr==3.1.0', 'console_scripts', 'pdb2pqr30')())
  File "/usr/bin/pdb2pqr30", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/pdb2pqr/__init__.py", line 10, in <module>
    from .main import main_driver, build_main_parser
  File "/usr/lib/python3.9/site-packages/pdb2pqr/main.py", line 16, in <module>
    import propka.lib
  File "/usr/lib/python3.9/site-packages/propka/lib.py", line 11, in <module>
    import pkg_resources
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'mmcif_pdbx>=1.1.2' distribution was not found and is required by pdb2pqr
```
The suspicious part for me is with VersionConflict stuff.

I have mmcif_pdbx installed as well as pdb2pqr:
```
$ pacman -Ql python-mmcif-pdbx 
python-mmcif-pdbx /usr/
python-mmcif-pdbx /usr/lib/
python-mmcif-pdbx /usr/lib/python3.9/
python-mmcif-pdbx /usr/lib/python3.9/site-packages/
python-mmcif-pdbx /usr/lib/python3.9/site-packages/mmcif_pdbx-0+unknown-py3.9.egg-info/
python-mmcif-pdbx /usr/lib/python3.9/site-packages/mmcif_pdbx-0+unknown-py3.9.egg-info/PKG-INFO
python-mmcif-pdbx /usr/lib/python3.9/site-packages/mmcif_pdbx-0+unknown-py3.9.egg-info/SOURCES.txt
python-mmcif-pdbx /usr/lib/python3.9/site-packages/mmcif_pdbx-0+unknown-py3.9.egg-info/dependency_links.txt
python-mmcif-pdbx /usr/lib/python3.9/site-packages/mmcif_pdbx-0+unknown-py3.9.egg-info/top_level.txt
python-mmcif-pdbx /usr/lib/python3.9/site-packages/mmcif_pdbx-0+unknown-py3.9.egg-info/zip-safe
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/__init__.py
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/__pycache__/
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/__pycache__/__init__.cpython-39.opt-1.pyc
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/__pycache__/__init__.cpython-39.pyc
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/__pycache__/_version.cpython-39.opt-1.pyc
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/__pycache__/_version.cpython-39.pyc
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/__pycache__/containers.cpython-39.opt-1.pyc
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/__pycache__/containers.cpython-39.pyc
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/__pycache__/errors.cpython-39.opt-1.pyc
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/__pycache__/errors.cpython-39.pyc
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/__pycache__/reader.cpython-39.opt-1.pyc
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/__pycache__/reader.cpython-39.pyc
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/__pycache__/writer.cpython-39.opt-1.pyc
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/__pycache__/writer.cpython-39.pyc
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/_version.py
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/containers.py
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/errors.py
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/reader.py
python-mmcif-pdbx /usr/lib/python3.9/site-packages/pdbx/writer.py

python-pdb2pqr /usr/
python-pdb2pqr /usr/bin/
python-pdb2pqr /usr/bin/dx2cube
python-pdb2pqr /usr/bin/inputgen
python-pdb2pqr /usr/bin/pdb2pqr30
python-pdb2pqr /usr/bin/psize
python-pdb2pqr /usr/lib/
python-pdb2pqr /usr/lib/python3.9/
python-pdb2pqr /usr/lib/python3.9/site-packages/
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr-3.1.0-py3.9.egg-info/
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr-3.1.0-py3.9.egg-info/PKG-INFO
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr-3.1.0-py3.9.egg-info/SOURCES.txt
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr-3.1.0-py3.9.egg-info/dependency_links.txt
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr-3.1.0-py3.9.egg-info/entry_points.txt
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr-3.1.0-py3.9.egg-info/requires.txt
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr-3.1.0-py3.9.egg-info/top_level.txt
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__init__.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__main__.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/__init__.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/__init__.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/__main__.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/__main__.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/_version.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/_version.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/aa.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/aa.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/biomolecule.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/biomolecule.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/cells.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/cells.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/cif.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/cif.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/config.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/config.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/debump.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/debump.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/definitions.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/definitions.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/forcefield.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/forcefield.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/inputgen.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/inputgen.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/io.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/io.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/main.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/main.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/na.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/na.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/pdb.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/pdb.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/psize.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/psize.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/quatfit.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/quatfit.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/residue.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/residue.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/run.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/run.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/structures.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/structures.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/topology.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/topology.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/utilities.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/__pycache__/utilities.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/_version.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/aa.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/biomolecule.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/cells.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/cif.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/config.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/AA.xml
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/AMBER.DAT
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/AMBER.names
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/CHARMM.DAT
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/CHARMM.names
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/HYDROGENS.xml
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/NA.xml
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/PARSE.DAT
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/PARSE.names
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/PATCHES.xml
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/PEOEPB.DAT
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/PEOEPB.names
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/SWANSON.DAT
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/SWANSON.names
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/TOPOLOGY.xml
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/TYL06.DAT
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/dat/TYL06.names
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/debump.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/definitions.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/forcefield.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/hydrogens/
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/hydrogens/__init__.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/hydrogens/__pycache__/
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/hydrogens/__pycache__/__init__.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/hydrogens/__pycache__/__init__.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/hydrogens/__pycache__/optimize.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/hydrogens/__pycache__/optimize.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/hydrogens/__pycache__/structures.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/hydrogens/__pycache__/structures.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/hydrogens/optimize.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/hydrogens/structures.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/inputgen.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/io.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/ligand/
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/ligand/__init__.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/ligand/__pycache__/
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/ligand/__pycache__/__init__.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/ligand/__pycache__/__init__.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/ligand/__pycache__/mol2.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/ligand/__pycache__/mol2.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/ligand/__pycache__/peoe.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/ligand/__pycache__/peoe.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/ligand/__pycache__/topology.cpython-39.opt-1.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/ligand/__pycache__/topology.cpython-39.pyc
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/ligand/mol2.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/ligand/peoe.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/ligand/topology.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/main.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/na.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/pdb.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/psize.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/quatfit.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/residue.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/run.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/structures.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/topology.py
python-pdb2pqr /usr/lib/python3.9/site-packages/pdb2pqr/utilities.py
```

**To Reproduce**
1. Run pdb2pqr
2. See error

**Expected behavior**
Working instance of pdb2pqr

**Desktop (please complete the following information):**
 - OS: Arch Linux rolling release

**Comment by sobolevnrm** [comment]
@intendo do you have time to look into this?

**Comment by intendo** [comment]
I think there may be a bug in the version number.
@dvdesolve can you post the output of the following steps:
```
python
import pdbx
pdbx.__version__
```

It should look something like:
```
# python
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdbx
>>> pdbx.__version__
'2.0.0'
```

**Comment by dvdesolve** [comment]
No, it still tells that version is `0+unknown`:
```
$ python
Python 3.9.2 (default, Feb 20 2021, 18:40:11) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdbx
>>> pdbx.__version__
'0+unknown'
>>>
```
mmcif_pdbx package is installed from pypi with [trivial installation script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-mmcif-pdbx)

**Comment by intendo** [comment]
@dvdesolve I am sorry about the version problems. We are trying to get a new release that should fix this. It looks like the versioneer code did not pick up the git tag correctly so the version is `0+unknown` instead of `2.0.0`. This is why the pdb2pqr is complaining that it can't find mmcif_pdbx `>=1.1.2`

@sobolevnrm and I are trying to get the a new version of mmcif_pdbx released soon. We will let you know when it fully tested and available.

**Comment by intendo** [comment]
@dvdesolve can you update your mmcif_pdbx and let us know if this problem is resolved for you?

**Comment by dvdesolve** [comment]
yep, all is working great. thank you a lot!

73, Viktor

**Comment by intendo** [comment]
Thanks, I will close this issue.
